InsuranceApp/Models/QuoteGenerator.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace InsuranceApp.Models
{
    public class QuoteGenerator
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public double Quote { get; set; }
    }
}

InsuranceApp/ViewModels/QuoteVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace InsuranceApp.ViewModels
{
    public class QuoteVm
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public double Quote { get; set; }
    }
}

InsuranceApp/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using InsuranceApp.ViewModels;

namespace InsuranceApp.Controllers
{
    public class AdminController : Controller
    {
        public ActionResult Index()
        {
            using (QuotesEntities db = new QuotesEntities())
            {

                var quotes = db.Quotes.Where(x => x.Removed == null).ToList();
                var QuoteVms = new List<QuoteVm>();
                foreach (var Quotes in quotes)
                {

                    //var is named "Quotes" rather than "Quote" because the title
                    //of the edmx table couldn't be the same as the parameter "Quote".
                    var QuoteVm = new QuoteVm();
                    QuoteVm.Id = Quotes.Id;
                    QuoteVm.Quote = Convert.ToDouble(Quotes.Quote);
                    QuoteVm.FirstName = Quotes.FirstName;
                    QuoteVm.LastName = Quotes.LastName;
                    QuoteVm.EmailAddress = Quotes.EmailAddress;                   
                    QuoteVms.Add(QuoteVm);
                }
                return View(QuoteVms);
            }
        }

        public ActionResult Remove(int Id)
        {
            using (QuotesEntities db = new QuotesEntities())
            {
                var quote = db.Quotes.Find(Id);
                quote.Removed = DateTime.Now;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

InsuranceApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using InsuranceApp.Models;
using InsuranceApp.ViewModels;

namespace InsuranceApp.Controllers
{
    public class HomeController : Controller
    {

        private readonly string connectionString = @"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=Quotes;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False";
        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Quote(string FirstName, string LastName, string EmailAddress, string DateOfBirth, string CarYear, string CarMake, string CarModel, string SpeedingTickets, string DUI, string Coverage)
        {
            if (string.IsNullOrEmpty(FirstName) || string.IsNullOrEmpty(LastName) || string.IsNullOrEmpty(EmailAddress) || string.IsNullOrEmpty(DateOfBirth) || string.IsNullOrEmpty(CarYear) || string.IsNullOrEmpty(CarMake) || string.IsNullOrEmpty(CarModel) || string.IsNullOrEmpty(SpeedingTickets) || string.IsNullOrEmpty(DUI) || string.IsNullOrEmpty(Coverage))

            {
                return View("~/Views/Shared/Error.cshtml");
            }

            else
            {

                DateTime Dob = Convert.ToDateTime(DateOfBirth);
                int age = 0;
                age = DateTime.Now.Year - Dob.Year;
                if (DateTime.Now.DayOfYear < Dob.DayOfYear)
                    age = age - 1;
                double total = 50;


                bool under25orOver100 = age < 25 || age > 100;
                if (under25orOver100)
                {
                    total = total + 25;
                }

                bool under18 = age < 18;
                if (under18)
                {

                    total = total + 100;
                }

                else
                {
                    total = total;
                }


                int carYear = Convert.ToInt32(CarYear);


                if (carYear < 2000 || carYear > 2015)
                {
                    total = total + 25;
                }

                else
                {
                    total = total;
                }

                if (CarMake == "porsche"||CarMake=="Porsche")
                {
                    total = total + 25;
                }
                else
                {
                    total = total;
                }
                if (CarMake == "porsche" && CarModel == "911 Carrera" ||CarMake== "Porsche" && CarModel == "911 Carrera")
                {
                    total = total + 25;
                }
                else
                {
                    total = total;
                }

                int tickets = Convert.ToInt32(SpeedingTickets);

                int ticketTotal = tickets * 10;

                total = total + ticketTotal;

                bool Dui = DUI == "yes"||DUI=="Yes";
                if (Dui)
                {
                    total = total + (total * .25);
                }
                else
                {
                    total = total;
                }

                bool FullCoverage = Coverage == "full coverage" || Coverage == "full" || Coverage == "Full Coverage" || Coverage == "Full";

                if (FullCoverage)
                {
                    total = total + (total * .5);
                }
                else
                {
                    total = total;
                }

                double Quote = total;
                
                ViewBag.Quote = "$" + Quote;
                

                using (QuotesEntities db = new QuotesEntities())
                {
                    var Quotes = new Quotes();
                    Quotes.FirstName = FirstName;
                    Quotes.LastName = LastName;
                    Quotes.EmailAddress = EmailAddress;
                    string Quote1 = Convert.ToString(Quote);
                    Quotes.Quote = Quote1;

                    db.Quotes.Add(Quotes);
                    db.SaveChanges();
                }
                return View("Success");
            }
        }
    }
}

InsuranceApp/Views/Admin/Index.cshtml
@using InsuranceApp.ViewModels
@model List<QuoteVm>

<div class="row no-gutters m-3">
    <div class="card col-sm-12 col-md-10 col-lg-6 mx-auto shadow">
        <div class="card-header text-center">
           
        </div>
        <br />
        <div>
            <h1 style="text-align:center; padding-top:40px;"><strong>Quotes Issued</strong></h1>
        </div>
        
        <div class="card-body">

            <h5>First Name<span style="margin-left:50px;">Last Name</span><span style="margin-left:50px;">Email Address</span><span style="margin-left:190px;">Quote</span></h5>
            @foreach (var Quote in Model)
            {
                using (Html.BeginForm("Remove", "Admin", FormMethod.Post))
                {
                    <input type="hidden" name="Id" value="@Quote.Id" />
                    <div class="row mb-3">
                        <div class="col-2">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-2">
                            @Quote.FirstName
                        </div>
                        <div class="col">
                            @Quote.LastName
                        </div>
                        <div class="col-4">
                            @Quote.EmailAddress
                        </div>
                        <div class="col">
                            @Quote.Quote
                        </div>
                        <div class="col">
                            <button type="submit" class="btn btn-inverse btn-block">
                                Remove Entry
                            </button>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</div>

InsuranceApp/Views/Home/Admin.cshtml
@using InsuranceApp.ViewModels
@model List<QuoteVm>



<div class="row no-gutters m-3">
    <div class="card col-sm-12 col-md-10 col-lg-6 mx-auto shadow">
        <div class="card-header text-center">         
            </div>
        <div class="card-body">
            @foreach (var Quote in Model)
            {
            <div class="row">
                <div class="col">                  
                    @Quote.FirstName
                </div>

                <div class="col">
                    <h1>Last Name</h1>
                    @Quote.LastName
                </div>

                <div class="col">
                    @Quote.EmailAddress
                </div>

                <div class="col">
                    @Quote.Quote
                </div>
            </div>
            }
        </div>
    </div>
</div>

InsuranceApp/Views/Home/Index.cshtml
<img style="z-index:-3; position:absolute; padding-top:40px; width:80%;" src="~/Content/images/rockoninsurance6.jpg"
<div class="row no-gutters m-3">

    <link href='https://fonts.googleapis.com/css?family=Alfa Slab One' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Akronim' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Annie Use Your Telescope' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Encode Sans Semi Expanded' rel='stylesheet'>
    <div class="card col-sm-12 col-md-10 col-lg-6 mx-auto shadow">

        <br />
        <div style="padding-top:100px; border:solid 2px #000" class="card-header bg-secondary text-center">
            <h5 style=" font-family: 'Akronim';font-size: 60px; color:#fff" class="m-0">Rock On! Auto Insurance</h5>
        </div>
        <div class="card-body">

            <div>
                <h1 style="font-family: 'Annie Use Your Telescope';font-size: 38px; text-align:center;  padding-bottom:10px;"><strong>Get your quote today!</strong></h1>
            </div>


            @using (Html.BeginForm("Quote", "Home", FormMethod.Post))
            {

                <div class="row no-gutters">
                    <div class="form-group col-md-12">
                        <input name="FirstName" type="text" class="form-control" placeholder="First Name" />
                    </div>

                    <div class="form-group col-md-12">
                        <input name="LastName" type="text" class="form-control" placeholder="Last Name" />
                    </div>

                    <div class="form-group col-md-12">
                        <input name="EmailAddress" type="email" class="form-control" placeholder="Email Address" />
                    </div>

                    <div class="form-group col-md-12">
                        <input name="DateOfBirth" type="text" class="form-control" placeholder="Date of Birth YYYY/MM/DD" />
                    </div>

                    <div class="form-group col-md-12">
                        <input name="CarYear" type="text" class="form-control" placeholder="Car Year" />
                    </div>

                    <div class="form-group col-md-12">
                        <input name="CarMake" type="text" class="form-control" placeholder="Car Make" />
                    </div>

                    <div class="form-group col-md-12">
                        <input name="CarModel" type="text" class="form-control" placeholder="Car Model" />
                    </div>
                    <div class="form-group col-md-12">
                        <input name="SpeedingTickets" type="text" class="form-control" placeholder="How many speeding tickets do you have?" />
                    </div>

                    <div class="form-group col-md-12">
                        <input name="DUI" type="text" class="form-control" placeholder="Have you ever had a DUI?" />
                    </div>
                    <div class="form-group col-md-12">
                        <input name="Coverage" type="text" class="form-control" placeholder="Would you like Full Coverage or Liability?" />
                    </div>
                    <button type="submit" class="btn btn-block btn-primary">Submit</button>
                </div>
            }
        </div>
    </div>
</div>

InsuranceApp/Views/Home/Success.cshtml
@{
    ViewBag.Title = "Success";
}
<br />
<div>
<br/>
<br />
   
<h4 style="padding-top:40px; padding-left:38px; font-size:30px; color:#fff; opacity:0.7;">Your monthly quote is:  @ViewBag.Quote</h4>
<br />


</div>

InsuranceApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <link href='https://fonts.googleapis.com/css?family=Akronim' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Carter One' rel='stylesheet'>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Insurance</title>
    @Styles.Render("~/Content/css")


</head>
<body style="background-color:#000;">
    
         @RenderBody()
         @Scripts.Render("~/bundles/jquery")
         @Scripts.Render("~bundles/bootstrap")
         @RenderSection("scripts", required: false)

    <nav class="navbar navbar-expand-sm navbar-dark fixed-top bg-dark">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"></button>
            <a style="font-family: 'Akronim';font-size: 37px; color:#FFFF66" class="navbar-brand" href="/"><i>Since 1996</i></a>

            <div class="navbar-collapse collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav mr-auto">

                    <li style="padding-left:36px;  font-family: 'Carter One'; padding-right:24px;"class="nav-item"><a style="color:#FF6600; font-size:25px;" href="/" class="nav-link">Home</a></li>
                    <li style="padding-left:36px;  font-family: 'Carter One'; padding-right:24px;" class="nav-item"><a style="color:#FF6600; font-size:25px;" href="/Admin" class="nav-link">Admin Page</a></li>
                    <li style="padding-left:36px;  font-family: 'Carter One'; padding-right:24px;" class="nav-item"><a style="color:#FF6600; font-size:25px;"href="/Home/Index" class="nav-link"> Get your Quote!</a></li>
                </ul>



            </div>
        </div>
    </nav>

</body>
</html>